"#version 410 core\n"
"out vec4 frag_colour;"
"uniform vec4 in_color;"
"uniform float border_width;"
"uniform float aspect;"
"in vec2 texCoord;"
"void main() {"
"   float maxX = 1.0 - border_width;"
"   float minX = border_width;"
"   float maxY = 1.0 - border_width;"
"   float minY = border_width;"
"   if (texCoord.x < maxX && texCoord.x > minX && texCoord.y < maxY && texCoord.y > minY) {"
"     frag_colour = in_color;"
"   } else {"
"     frag_colour = vec4(1.0f, 1.0f, 1.0f, 1.0f);"
"   }"
"}"
