"#version 410 core\n"
"layout(location = 0) in vec3 position;"
"layout(location = 1) in vec2 uv;"
"layout(location = 2) in float stretch;"
"out vec2 texCoord;"
"out float stretch_x;"
"uniform float aspect;"
"void main() {"
"    texCoord = uv;"
"    gl_Position = vec4(position.x / aspect, position.y, position.z, 1.0);"
"    stretch_x = stretch;"
"}"